#!/usr/bin/env bash
set -e
set -o pipefail

. scripts/launch/setup_env "${sigopt_server_config_file:-config/development.json}"
./scripts/launch/compose run --rm generate-routes
./scripts/launch/compose run --rm --publish=5900:5900 test-runner python -m test.test_runner --config-file "$sigopt_server_config_file" "$@"
