version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    reviewers:
      - "sigopt/eng"
    schedule:
      interval: "weekly"
    versioning-strategy: "lockfile-only"
  - package-ecosystem: "pip"
    directory: "/"
    reviewers:
      - "sigopt/eng"
    schedule:
      interval: "weekly"
    versioning-strategy: "lockfile-only"
