title = "SigOpt Server"

[tool.black]
line-length = 120

include = '/(src/python/zigopt|test|sigoptlite)/.*\.py$'

[tool.bandit]
exclude_dirs = [
  'scripts',
  'test',
  'tools',
  'docker'
]
tests = [
  'B301',
  'B302',
  'B303',
  'B304',
  'B305',
  'B306',
  'B308',
  'B310',
  'B311',
  'B312',
  'B313',
  'B314',
  'B315',
  'B316',
  'B317',
  'B318',
  'B319',
  'B320',
  'B321',
  'B323',
  'B324',
  'B401',
  'B402',
  'B403',
  'B404',
  'B405',
  'B406',
  'B407',
  'B408',
  'B409',
  'B410',
  'B411',
  'B412',
  'B413'
]
skips = [
  'B101',
  'B102',
  'B103',
  'B104',
  'B105',
  'B106',
  'B107',
  'B108',
  'B110',
  'B112',
  'B201',
  'B501',
  'B502',
  'B503',
  'B504',
  'B505',
  'B506',
  'B507',
  'B601',
  'B602',
  'B603',
  'B604',
  'B605',
  'B606',
  'B607',
  'B608',
  'B609',
  'B610',
  'B611',
  'B701',
  'B702',
  'B703'
]

[tool.bandit.any_other_function_with_shell_equals_true]
no_shell = [
  'os.execl',
  'os.execle',
  'os.execlp',
  'os.execlpe',
  'os.execv',
  'os.execve',
  'os.execvp',
  'os.execvpe',
  'os.spawnl',
  'os.spawnle',
  'os.spawnlp',
  'os.spawnlpe',
  'os.spawnv',
  'os.spawnve',
  'os.spawnvp',
  'os.spawnvpe',
  'os.startfile'
]
shell = [
  'os.system',
  'os.popen',
  'os.popen2',
  'os.popen3',
  'os.popen4',
  'popen2.popen2',
  'popen2.popen3',
  'popen2.popen4',
  'popen2.Popen3',
  'popen2.Popen4',
  'commands.getoutput',
  'commands.getstatusoutput'
]
subprocess = [
  'subprocess.Popen',
  'subprocess.call',
  'subprocess.check_call',
  'subprocess.check_output',
  'subprocess.run'
]

[tool.bandit.assert_used]
skips = []

[tool.bandit.hardcoded_tmp_directory]
tmp_dirs = [
  '/tmp',
  '/var/tmp',
  '/dev/shm'
]

[tool.bandit.linux_commands_wildcard_injection]
no_shell = [
  'os.execl',
  'os.execle',
  'os.execlp',
  'os.execlpe',
  'os.execv',
  'os.execve',
  'os.execvp',
  'os.execvpe',
  'os.spawnl',
  'os.spawnle',
  'os.spawnlp',
  'os.spawnlpe',
  'os.spawnv',
  'os.spawnve',
  'os.spawnvp',
  'os.spawnvpe',
  'os.startfile'
]
shell = [
  'os.system',
  'os.popen',
  'os.popen2',
  'os.popen3',
  'os.popen4',
  'popen2.popen2',
  'popen2.popen3',
  'popen2.popen4',
  'popen2.Popen3',
  'popen2.Popen4',
  'commands.getoutput',
  'commands.getstatusoutput'
]
subprocess = [
  'subprocess.Popen',
  'subprocess.call',
  'subprocess.check_call',
  'subprocess.check_output',
  'subprocess.run'
]

[tool.bandit.ssl_with_bad_defaults]
bad_protocol_versions = [
  'PROTOCOL_SSLv2',
  'SSLv2_METHOD',
  'SSLv23_METHOD',
  'PROTOCOL_SSLv3',
  'PROTOCOL_TLSv1',
  'SSLv3_METHOD',
  'TLSv1_METHOD'
]

[tool.bandit.ssl_with_bad_version]
bad_protocol_versions = [
  'PROTOCOL_SSLv2',
  'SSLv2_METHOD',
  'SSLv23_METHOD',
  'PROTOCOL_SSLv3',
  'PROTOCOL_TLSv1',
  'SSLv3_METHOD',
  'TLSv1_METHOD'
]

[tool.bandit.start_process_with_a_shell]
no_shell = [
  'os.execl',
  'os.execle',
  'os.execlp',
  'os.execlpe',
  'os.execv',
  'os.execve',
  'os.execvp',
  'os.execvpe',
  'os.spawnl',
  'os.spawnle',
  'os.spawnlp',
  'os.spawnlpe',
  'os.spawnv',
  'os.spawnve',
  'os.spawnvp',
  'os.spawnvpe',
  'os.startfile'
]
shell = [
  'os.system',
  'os.popen',
  'os.popen2',
  'os.popen3',
  'os.popen4',
  'popen2.popen2',
  'popen2.popen3',
  'popen2.popen4',
  'popen2.Popen3',
  'popen2.Popen4',
  'commands.getoutput',
  'commands.getstatusoutput'
]
subprocess = [
  'subprocess.Popen',
  'subprocess.call',
  'subprocess.check_call',
  'subprocess.check_output',
  'subprocess.run'
]

[tool.bandit.start_process_with_no_shell]
no_shell = [
  'os.execl',
  'os.execle',
  'os.execlp',
  'os.execlpe',
  'os.execv',
  'os.execve',
  'os.execvp',
  'os.execvpe',
  'os.spawnl',
  'os.spawnle',
  'os.spawnlp',
  'os.spawnlpe',
  'os.spawnv',
  'os.spawnve',
  'os.spawnvp',
  'os.spawnvpe',
  'os.startfile'
]
shell = [
  'os.system',
  'os.popen',
  'os.popen2',
  'os.popen3',
  'os.popen4',
  'popen2.popen2',
  'popen2.popen3',
  'popen2.popen4',
  'popen2.Popen3',
  'popen2.Popen4',
  'commands.getoutput',
  'commands.getstatusoutput'
]
subprocess = [
  'subprocess.Popen',
  'subprocess.call',
  'subprocess.check_call',
  'subprocess.check_output',
  'subprocess.run'
]

[tool.bandit.start_process_with_partial_path]
no_shell = [
  'os.execl',
  'os.execle',
  'os.execlp',
  'os.execlpe',
  'os.execv',
  'os.execve',
  'os.execvp',
  'os.execvpe',
  'os.spawnl',
  'os.spawnle',
  'os.spawnlp',
  'os.spawnlpe',
  'os.spawnv',
  'os.spawnve',
  'os.spawnvp',
  'os.spawnvpe',
  'os.startfile'
]
shell = [
  'os.system',
  'os.popen',
  'os.popen2',
  'os.popen3',
  'os.popen4',
  'popen2.popen2',
  'popen2.popen3',
  'popen2.popen4',
  'popen2.Popen3',
  'popen2.Popen4',
  'commands.getoutput',
  'commands.getstatusoutput'
]
subprocess = [
  'subprocess.Popen',
  'subprocess.call',
  'subprocess.check_call',
  'subprocess.check_output',
  'subprocess.run'
]

[tool.bandit.subprocess_popen_with_shell_equals_true]
no_shell = [
  'os.execl',
  'os.execle',
  'os.execlp',
  'os.execlpe',
  'os.execv',
  'os.execve',
  'os.execvp',
  'os.execvpe',
  'os.spawnl',
  'os.spawnle',
  'os.spawnlp',
  'os.spawnlpe',
  'os.spawnv',
  'os.spawnve',
  'os.spawnvp',
  'os.spawnvpe',
  'os.startfile'
]
shell = [
  'os.system',
  'os.popen',
  'os.popen2',
  'os.popen3',
  'os.popen4',
  'popen2.popen2',
  'popen2.popen3',
  'popen2.popen4',
  'popen2.Popen3',
  'popen2.Popen4',
  'commands.getoutput',
  'commands.getstatusoutput'
]
subprocess = [
  'subprocess.Popen',
  'subprocess.call',
  'subprocess.check_call',
  'subprocess.check_output',
  'subprocess.run'
]

[tool.bandit.subprocess_without_shell_equals_true]
no_shell = [
  'os.execl',
  'os.execle',
  'os.execlp',
  'os.execlpe',
  'os.execv',
  'os.execve',
  'os.execvp',
  'os.execvpe',
  'os.spawnl',
  'os.spawnle',
  'os.spawnlp',
  'os.spawnlpe',
  'os.spawnv',
  'os.spawnve',
  'os.spawnvp',
  'os.spawnvpe',
  'os.startfile'
]
shell = [
  'os.system',
  'os.popen',
  'os.popen2',
  'os.popen3',
  'os.popen4',
  'popen2.popen2',
  'popen2.popen3',
  'popen2.popen4',
  'popen2.Popen3',
  'popen2.Popen4',
  'commands.getoutput',
  'commands.getstatusoutput'
]
subprocess = [
  'subprocess.Popen',
  'subprocess.call',
  'subprocess.check_call',
  'subprocess.check_output',
  'subprocess.run'
]

[tool.bandit.try_except_continue]
check_typed_exception = false

[tool.bandit.try_except_pass]
check_typed_exception = false

[tool.bandit.weak_cryptographic_key]
weak_key_size_dsa_high = 1024
weak_key_size_dsa_medium = 2048
weak_key_size_ec_high = 160
weak_key_size_ec_medium = 224
weak_key_size_rsa_high = 1024
weak_key_size_rsa_medium = 2048
