version: 2.1

orbs:
  slack: circleci/slack@4.4.4

commands:
  attach:
    steps:
      - attach_workspace:
          at: /home/circleci
  install-submodules:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "87:b9:24:d8:b8:2f:de:8b:44:bf:da:d4:d7:2c:e1:1a"
      - run:
          command: |
            git submodule init
            git submodule sync
            git submodule update
  install-python-libraries:
    steps:
      - run: pip install pipenv
      - run: pipenv install --quiet --deploy --dev --python=3.10
  update-docker-cli:
    steps:
      - run: sudo mkdir -p /etc/apt/keyrings
      - run: sudo apt-get remove -yqq docker-ce-rootless-extras docker-scan-plugin
      - run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      - run: |
          echo \
            "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu focal stable" \
           | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      - run: apt-cache madison docker-ce-cli | awk '{ print $3 }'
      - run: |
          sudo apt-get update -yqq && sudo apt-get install -yqq \
            docker-ce-cli=5:20.10.23~3-0~ubuntu-focal \
            docker-compose-plugin=2.16.0-1~ubuntu.20.04~focal
      - run: docker version
  sigopt-ninja-dns:
    steps:
      - run:
          name: Add sigopt.ninja DNS entry
          command: echo '127.0.0.1 sigopt.ninja' | sudo tee -a /etc/hosts
  compile-protobuf:
    steps:
      - run: source .env && sudo ./tools/protobuf/install.sh "$PROTOBUF_VERSION"
      - run: ./tools/protobuf/compile.sh
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project/src/python/zigopt/protobuf/gen
  install-node:
    steps:
      - run: cp yarn.lock yarn.lock.old
      - run: yarn install
      - run: if ! diff yarn.lock yarn.lock.old >/dev/null; then echo 'yarn.lock has changed, make sure to `yarn install` and commit it'; exit 1; fi
      - run: rm yarn.lock.old
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project/node_modules
  start-service:
    steps:
      - run:
          name: << parameters.description >>
          command: ./ci/compose.sh up << parameters.service >>
          background: true
    parameters:
      description:
        type: string
      service:
        type: string
  start-sigopt-service:
    steps:
      - start-service:
          description: SigOpt << parameters.description >>
          service: << parameters.service >>
    parameters:
      description:
        type: string
      service:
        type: string
  docker-test-setup:
    steps:
      - run: make submodules
      - sigopt-ninja-dns
  initialize-config-directory:
    steps:
      - run:
          name: Initialize SigOpt Server config directory
          command: |
            ./ci/compose.sh run -Ti --rm init-config sh -e \<<EOF
              cp /sigopt-server/config/circleci/* /etc/sigopt/server-config/
              echo CHANGEME123 >/etc/minio/password.txt
            EOF
  start-web-server:
    steps:
      - start-sigopt-service:
          description: Web Server
          service: web-server
      - run: ./ci/wait_for.sh url https://sigopt.ninja:4443/login
  store-junit-test-results:
    steps:
      - store_test_results:
          path: junit-results
      - store_artifacts:
          path: junit-results
          prefix: junit-results
  generate-openapi-docs:
    steps:
      - checkout
      - attach
      - install-python-libraries
      - run:
          name: Generate swagger file
          command: pipenv run env SIGOPT_SERVER_CONFIG_DIR=./config/circleci ./pp src/python/zigopt/api/documentation.py
          environment:
            SIGOPT_SWAGGER_PATH: /home/circleci/project/
            SIGOPT_SWAGGER_FILENAME: swagger.json
      - persist_to_workspace:
          root: /home/circleci/
          paths:
            - project
  validate-openapi-docs:
    steps:
      - attach
      - install-submodules
      - run:
          name: Check that swagger file exists and validate it with swagger validator
          command: node ./ci/validate_swagger.js /home/circleci/project/swagger.json
  notify-slack-on-fail:
    steps:
      - slack/notify:
          branch_pattern: master
          channel: sigopt-platform-ci
          event: fail
          custom: |
            {
              "blocks": [
                {
                  "text": {
                    "text": "*$CIRCLE_JOB* _failed_ in *$CIRCLE_PROJECT_REPONAME* (*$CIRCLE_BRANCH*): <${CIRCLE_BUILD_URL}|View Workflow>",
                    "type": "mrkdwn"
                  },
                  "type": "section"
                }
              ]
            }

executors:
  sigopt-build:
    machine:
      image: &ubuntu-executor-image ubuntu-2004:2022.10.1
    resource_class: large
  basic:
    docker:
      - image: cimg/base:current-22.04
  sigopt-python-only:
    docker:
      - image: cimg/python:3.10
    resource_class: small
  sigopt-node-only:
    docker:
      - image: cimg/node:16.18
    resource_class: small
  sigopt-mcafee:
    machine:
      image: *ubuntu-executor-image
    resource_class: xlarge
  sigopt-lite:
    docker:
      - image: cimg/base:2022.11
    resource_class: small

jobs:
  checkout-code:
    docker:
      - image: alpine/git
    resource_class: small
    steps:
      - checkout
      - run: git reflog expire --expire=now --all
      - run: git repack -ad
      - run: git prune
      - persist_to_workspace:
          root: /root
          paths:
            - .ssh
            - project
  test-docker-development:
    executor: sigopt-build
    resource_class: xlarge
    steps:
      - checkout
      - update-docker-cli
      - run: ./ci/create_development_tls_certs.sh
      - sigopt-ninja-dns
      - run: make submodules fix-db setup-cookiejar setup-filestorage
      - run: ./scripts/launch/start_zigopt_services.sh || ./scripts/launch/start_zigopt_services.sh
      - run:
          name: Development services
          command: ./scripts/launch/all_live.sh
          background: true
      - run: ./ci/wait_for.sh url https://sigopt.ninja:4443/login
      - run: "./ci/wait_for.sh url https://sigopt.ninja:4443/api/ --user client_token:"
      - run: |
          curl -fk -X POST https://sigopt.ninja:4443/api/v1/sessions -d '{"email": "owner@sigopt.ninja", "password": "owner"}'
      - run: |
          ./test/test_dev_env.sh \
            test/integration/browser/tests/interaction/global/email_test.py \
            test/integration/v1/endpoints/training_runs/files_test.py
  compile-protobuf:
    executor: basic
    resource_class: small
    steps:
      - checkout
      - compile-protobuf
  setup-web:
    executor: sigopt-node-only
    resource_class: large
    steps:
      - checkout
      - run: sudo apt-get update -yqq && sudo apt-get install nasm
      - install-node
  documentation-generation:
    executor: sigopt-python-only
    steps:
      - generate-openapi-docs
  documentation-validation:
    executor: sigopt-node-only
    steps:
      - validate-openapi-docs
  eval-circleci:
    docker:
      - image: circleci/buildpack-deps:curl
    resource_class: small
    steps:
      # Fails on non-20x error code, https://superuser.com/a/1249678
      - run: "curl -X POST --silent --show-error --fail -u ${EVAL_FRAMEWORK_BUILD_TOKEN}: https://circleci.com/api/v2/project/gh/sigopt/eval-framework/pipeline"

workflows:
  main:
    jobs:
      - checkout-code
      - test-docker-development
      - setup-web
      - compile-protobuf
      - documentation-generation:
          requires:
            - compile-protobuf
      - documentation-validation:
          requires:
            - setup-web
            - documentation-generation
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
