# Copyright © 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache License 2.0
CONSTRAINTS_REASON = "experiment with constraints"
MAX_DIMENSION_WITH_CONSTRAINTS = 100
MAX_OBSERVATIONS_WITH_CONSTRAINTS = 2500
MAX_LINEAR_CONSTRAINTS = 10

CONDITIONALS_REASON = "experiment with conditionals"
MAX_DIMENSION_WITH_CONDITIONALS = 20
MAX_OBSERVATIONS_WITH_CONDITIONALS = 600
MAX_CONDITIONALS_BREADTH = 6
