#!/usr/bin/env bash
set -e
set -o pipefail

export COMPOSE_PROJECT_NAME="${CIRCLE_SHA1}_${CIRCLE_JOB}_${CIRCLE_NODE_INDEX}"
export TEST_RUNNER_NAME="${TEST_RUNNER_NAME:-test-runner}"
export TAG="$CIRCLE_SHA1"
export SIGOPT_CONFIG_FILE=config/circleci.json

exec docker-compose --file=docker-compose.yml --env-file=./.env "$@"
