name: Coverity Scan
permissions: read-all
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  coverity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git ls-files > git-ls-files.lst
      - uses: vapier/coverity-scan-action@v1
        with:
          project: sigopt-server
          email: ${{ secrets.COVERITY_SCAN_EMAIL }}
          token: ${{ secrets.COVERITY_SCAN_TOKEN }}
          build_language: other
          command: "--no-command --fs-capture-list git-ls-files.lst"
