name: integration tests
permissions: read-all
run-name: Integration tests for ${{ github.repository }}@${{ github.ref }}
on:
  push: {}
jobs:
  service:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: ./ci/run_integration_test.sh test/integration/service/
      - name: Docker logs
        if: always()
        run: |
          set +e
          ./ci/compose.sh logs postgres
          ./ci/compose.sh logs redis
          ./ci/compose.sh logs minio
          ./ci/compose.sh logs smtp
  v1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite:
          - admin
          - authentication
          - endpoints
          - features
          - requests
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: ./ci/create_development_tls_certs.sh
      - run: ./ci/run_integration_test.sh test/integration/v1/${{ matrix.suite }}/ qworker qworker-analytics api nginx
      - name: Docker logs
        if: always()
        run: |
          set +e
          ./ci/compose.sh logs postgres
          ./ci/compose.sh logs redis
          ./ci/compose.sh logs minio
          ./ci/compose.sh logs smtp
          ./ci/compose.sh logs qworker
          ./ci/compose.sh logs qworker-analytics
          ./ci/compose.sh logs api
          ./ci/compose.sh logs nginx
  web:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: ./ci/create_development_tls_certs.sh
      - run: make submodules
      - run: ./ci/run_integration_test.sh test/integration/web/ qworker qworker-analytics api web-server nginx
      - name: Docker logs
        if: always()
        run: |
          set +e
          ./ci/compose.sh logs postgres
          ./ci/compose.sh logs redis
          ./ci/compose.sh logs minio
          ./ci/compose.sh logs smtp
          ./ci/compose.sh logs qworker
          ./ci/compose.sh logs qworker-analytics
          ./ci/compose.sh logs api
          ./ci/compose.sh logs web-server
          ./ci/compose.sh logs nginx
  browser:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite:
          - admin
          - experiment
          - global
          - home
          - organization
          - project
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: ./ci/create_development_tls_certs.sh
      - run: make submodules
      - run: ./ci/run_integration_test.sh test/integration/browser/tests/interaction/${{ matrix.suite }} qworker qworker-analytics api web-server nginx
      - name: Docker logs
        if: always()
        run: |
          set +e
          ./ci/compose.sh logs postgres
          ./ci/compose.sh logs redis
          ./ci/compose.sh logs minio
          ./ci/compose.sh logs smtp
          ./ci/compose.sh logs qworker
          ./ci/compose.sh logs qworker-analytics
          ./ci/compose.sh logs api
          ./ci/compose.sh logs web-server
          ./ci/compose.sh logs nginx
  worker-health:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: ./ci/init_config.sh
      - run: ./ci/run_container_bg.sh postgres
      - run: ./ci/run_container_fg.sh createdb
      - run: ./ci/compose.sh build --progress=plain qworker qworker-analytics
      - run: ./ci/worker_health_fail.sh
      - run: ./ci/run_container_bg.sh redis
      - run: ./ci/worker_health_pass.sh
      - name: Docker logs
        if: always()
        run: |
          set +e
          ./ci/compose.sh logs postgres
          ./ci/compose.sh logs redis
          ./ci/compose.sh logs qworker
          ./ci/compose.sh logs qworker-analytics
