name: test local deployments
permissions: read-all
run-name: Test local deployments for ${{ github.repository }}@${{ github.ref }}
on:
  push: {}
  schedule:
    - cron: "0 8,16 * * *"
jobs:
  main-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo '127.0.0.1 sigopt.ninja' | sudo tee -a /etc/hosts
      - run: mkdir -p scratch
      - run: |
          set -o pipefail
          EDITOR=true ./setup.sh | tee scratch/setup_output.log
      - run: ./start.sh &
      - run: ./ci/wait_for.sh url https://sigopt.ninja:4443/login
      - run: ./ci/wait_for.sh url https://sigopt.ninja:4443/api/health
      - run: |
          EMAIL="$(tail -n 2 scratch/setup_output.log | grep -E '^  email:' | awk -F': ' '{ print $2 }')"
          PASSWORD="$(tail -n 2 scratch/setup_output.log | grep -E '^  password:' | awk -F': ' '{ print $2 }')"
          curl -fk -X POST https://sigopt.ninja:4443/api/v1/sessions -d '{"email": "'"$EMAIL"'", "password": "'"$PASSWORD"'"}'
      - name: Docker logs
        if: always()
        run: |
          set +e
          docker compose logs postgres
          docker compose logs redis
          docker compose logs minio
          docker compose logs web-server
          docker compose logs api
          docker compose logs nginx
          docker compose logs qworker
          docker compose logs qworker-analytics
  development-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo '127.0.0.1 sigopt.ninja' | sudo tee -a /etc/hosts
      - run: ./ci/create_development_tls_certs.sh
      - run: make submodules fix-db setup-cookiejar setup-filestorage
      - run: ./scripts/launch/start_zigopt_services.sh || ./scripts/launch/start_zigopt_services.sh
      - run: BUILD_ONLY=x ./scripts/launch/all_live.sh
      - run: ./scripts/launch/all_live.sh &
      - run: ./ci/wait_for.sh url https://sigopt.ninja:4443/login
      - run: "./ci/wait_for.sh url https://sigopt.ninja:4443/api/ --user client_token:"
      - run: |
          curl -fk -X POST https://sigopt.ninja:4443/api/v1/sessions -d '{"email": "owner@sigopt.ninja", "password": "owner"}'
      - run: |
          ./test/test_dev_env.sh \
            test/integration/browser/tests/interaction/global/email_test.py \
            test/integration/v1/endpoints/training_runs/files_test.py
      - name: Docker logs
        if: always()
        run: |
          set +e
          ./scripts/launch/compose.sh logs postgres
          ./scripts/launch/compose.sh logs redis
          ./scripts/launch/compose.sh logs minio
          ./scripts/launch/compose.sh logs smtp
          ./scripts/launch/compose.sh logs web-server
          ./scripts/launch/compose.sh logs web-client
          ./scripts/launch/compose.sh logs api
          ./scripts/launch/compose.sh logs nginx
          ./scripts/launch/compose.sh logs qworker
          ./scripts/launch/compose.sh logs qworker-analytics
