name: SigOpt Server pre-commit checks
run-name: Pre-commit checks for ${{ github.repository }}@${{ github.ref }}
on:
  push: {}
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hook:
          - hadolint-docker
          - mypy
          - pylint
          - shellcheck
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: pip install pipenv
      - run: pipenv install --quiet --deploy --dev
      - run: yarn install
      - run: source .env && sudo ./tools/protobuf/install.sh "$PROTOBUF_VERSION"
      - run: pipenv run ./tools/protobuf/compile.sh
      - run: pipenv run pre-commit run --all-files ${{ matrix.hook }}
      - run: git diff
  pre-commit-eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: pip install pipenv pre-commit
      - run: yarn install
      - run: pipenv run pre-commit run --all-files eslint
      - run: git diff
