name: security checks
run-name: Security checks for ${{ github.repository }}@${{ github.ref }}
on:
  push: {}
  schedule:
    - cron: "0 8,16 * * *"
jobs:
  trivy-scan-fs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - id: trivy
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: aquasecurity
          repo: trivy
      - run: |
          TRIVY_VERSION="${{ steps.trivy.outputs.release }}"
          TRIVY_VERSION="${TRIVY_VERSION#v}"
          curl -fSsLo trivy.deb \
            "https://github.com/aquasecurity/trivy/releases/download/v$TRIVY_VERSION/trivy_${TRIVY_VERSION}_Linux-64bit.deb"
          sudo dpkg -i trivy.deb
          rm trivy.deb
      - run: mkdir -p artifacts/trivy && trivy fs . --debug
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: trivy-fs-results
          path: artifacts/trivy/results.json
  trivy-scan-images:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - id: trivy
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: aquasecurity
          repo: trivy
      - run: |
          TRIVY_VERSION="${{ steps.trivy.outputs.release }}"
          TRIVY_VERSION="${TRIVY_VERSION#v}"
          curl -fSsLo trivy.deb \
            "https://github.com/aquasecurity/trivy/releases/download/v$TRIVY_VERSION/trivy_${TRIVY_VERSION}_Linux-64bit.deb"
          sudo dpkg -i trivy.deb
          rm trivy.deb
      - run: make submodules
      - run: ./ci/trivy_scan_images.sh --ignore-unfixed --debug
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: trivy-images-results
          path: artifacts/trivy/
