name: security checks
run-name: Security checks for ${{ github.repository }}@${{ github.ref }}
on:
  push: {}
  schedule:
    - cron: "0 8,16 * * *"
jobs:
  trivy-scan-fs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: mkdir -p artifacts/trivy
      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          trivy-config: trivy.yaml
  trivy-scan-images:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: make submodules
      - run: ./ci/trivy_build_images.sh --ignore-unfixed --debug
      - run: mkdir -p artifacts/trivy
      - name: Trivy scan nginx
        if: always()
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: sigopt/nginx:scan
          ignore-unfixed: true
          trivy-config: trivy.yaml
      - name: Trivy scan web
        if: always()
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: sigopt/web:scan
          ignore-unfixed: true
          trivy-config: trivy.yaml
      - name: Trivy scan zigopt
        if: always()
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: sigopt/zigopt:scan
          ignore-unfixed: true
          trivy-config: trivy.yaml
