name: auto upgrades
run-name: Auto upgrades for ${{ github.repository }}@${{ github.ref }}
on:
  push: {}
jobs:
  yarn:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: yarn upgrade
