name: auto upgrades
run-name: Auto upgrades for ${{ github.repository }}@${{ github.ref }}
on:
  push: {}
jobs:
  yarn:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: yarn upgrade
      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: yarn upgrade
          title: "Weekly `yarn upgrade` - ${{ steps.date.outputs.DATE }}"
          body: "Automatic changes made by Github Actions workflow specified in: `.github/workflows/upgrades.yml`"
          reviewers: dwanderson-intel,tjs-intel
          branch: auto-upgrade/yarn-upgrade-${{ steps.date.outputs.DATE }}
          delete-branch: true
          token: ${{ secrets.AUTO_UPGRADES_GITHUB_TOKEN }}
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-url }}
        run: |
          echo "Pull Request Created - ${{ steps.cpr.outputs.pull-request-url }}"
